model_config:
  name: Qwen/Qwen2.5-3B-Instruct
  max_length: 128
  temperature: 0.1
embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
prompt_name: CounterfactualPromptV1
chunk_size: 2048
chunk_overlap: 50
documents:
  type: clash