model_config:
  name: Qwen/Qwen2.5-14B-Instruct
  max_length: 1024
  temperature: 0.1
embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
prompt_name: GithubContextPromptV1
chunk_size: 1200
chunk_overlap: 50
documents:
  type: medical